development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: db
  password: ttpoz88__
    
test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: db
  password: ttpoz88__